# Generated by Django 4.1 on 2023-08-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnet_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_1', models.CharField(default='', max_length=200)),
                ('value_2', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
